bad short term fix while I figure out how to do spring class injection
Class com.lists.handler.DynamoThingStreamHandler has no public zero-argument constructor: java.lang.Exception
java.lang.Exception: Class com.lists.handler.DynamoThingStreamHandler has no public zero-argument constructor
Caused by: java.lang.NoSuchMethodException: com.lists.handler.DynamoThingStreamHandler.<init>()
	at java.base/java.lang.Class.getConstructor0(Unknown Source)
	at java.base/java.lang.Class.getConstructor(Unknown Source)